# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2026_03_28_200011) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "change_orders", force: :cascade do |t|
    t.string "cname"
    t.string "address"
    t.string "phone"
    t.date "date"
    t.string "commit"
    t.string "job"
    t.string "email"
    t.string "vendor"
    t.string "code"
    t.string "job_site"
    t.decimal "Contract"
    t.decimal "corder1"
    t.decimal "corder2"
    t.decimal "corder3"
    t.decimal "corder4"
    t.decimal "corder5"
    t.decimal "total"
    t.string "description"
    t.integer "number"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "cost_sheet_id"
    t.integer "count_number"
    t.integer "daily_number"
    t.decimal "cost"
    t.string "mdefault1"
    t.string "mdescription1"
    t.decimal "mtotal1"
    t.string "mdefault2"
    t.string "mdescription2"
    t.decimal "mtotal2"
    t.string "mdefault3"
    t.string "mdescription3"
    t.decimal "mtotal3"
    t.index ["cost_sheet_id"], name: "index_change_orders_on_cost_sheet_id"
  end

  create_table "cost_sheets", force: :cascade do |t|
    t.decimal "totalcost"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "alabor1"
    t.string "adescription1"
    t.integer "adays1"
    t.integer "aemp1"
    t.decimal "apricing1"
    t.decimal "atotal1"
    t.integer "alabor2"
    t.string "adescription2"
    t.integer "adays2"
    t.integer "aemp2"
    t.decimal "apricing2"
    t.decimal "atotal2"
    t.integer "alabor3"
    t.string "adescriptio3"
    t.integer "adays3"
    t.integer "aemp3"
    t.decimal "apricing3"
    t.decimal "atotal3"
    t.integer "alabor4"
    t.string "adescription4"
    t.integer "adays4"
    t.integer "aemp4"
    t.decimal "apricing4"
    t.decimal "atotal4"
    t.integer "alabor5"
    t.string "adescription5"
    t.integer "adays5"
    t.integer "aemp5"
    t.decimal "apricing5"
    t.decimal "atotal5"
    t.integer "alabor6"
    t.string "adescription6"
    t.integer "adays6"
    t.integer "aemp6"
    t.decimal "apricing6"
    t.decimal "atotal6"
    t.integer "alabor7"
    t.string "adescription7"
    t.integer "adays7"
    t.integer "aemp7"
    t.decimal "apricing7"
    t.decimal "atotal7"
    t.integer "alabor8"
    t.string "adescription8"
    t.integer "adays8"
    t.integer "aemp8"
    t.decimal "apricing8"
    t.decimal "atotal8"
    t.integer "alabor9"
    t.string "adescription9"
    t.integer "adays9"
    t.integer "aemp9"
    t.decimal "apricing9"
    t.decimal "atotal9"
    t.string "eexcavator1"
    t.string "edescription1"
    t.integer "eqty1"
    t.integer "edaywk1"
    t.decimal "epricing1"
    t.decimal "etotal1"
    t.string "eexcavator2"
    t.string "edescription2"
    t.integer "eqty2"
    t.integer "edaywk2"
    t.decimal "epricing2"
    t.decimal "etotal2"
    t.string "scisso3"
    t.string "edescription3"
    t.integer "eqty3"
    t.integer "edaywk3"
    t.decimal "epricing3"
    t.decimal "etotal3"
    t.string "loader4"
    t.string "edescription4"
    t.integer "eqty4"
    t.integer "edaywk4"
    t.decimal "epricing4"
    t.decimal "etotal4"
    t.string "etrunck5"
    t.string "edescription5"
    t.integer "eqty5"
    t.integer "edaywk5"
    t.decimal "epricing5"
    t.decimal "etotal5"
    t.string "ebobcat6"
    t.string "edescription6"
    t.integer "eqty6"
    t.integer "edaywk6"
    t.decimal "epricing6"
    t.decimal "etotal6"
    t.decimal "etotal"
    t.string "edefault7"
    t.string "edescription7"
    t.integer "eqty7"
    t.integer "edaywk7"
    t.decimal "epricing7"
    t.decimal "etotal7"
    t.string "edefault8"
    t.string "edescription8"
    t.integer "eqty8"
    t.integer "edaywk8"
    t.decimal "epricing8"
    t.decimal "etotal8"
    t.string "ttrash1"
    t.string "tdescription1"
    t.integer "tqtyyds1"
    t.integer "tdays1"
    t.decimal "tpricing1"
    t.string "tconcrete2"
    t.string "tdescription2"
    t.integer "tqtyyds2"
    t.integer "tdays2"
    t.decimal "tpricing2"
    t.string "tasphalt3"
    t.string "tdescription3"
    t.integer "tqtyyds3"
    t.integer "tdays3"
    t.decimal "tpricing3"
    t.decimal "ttotal"
    t.string "pdemo1"
    t.string "pdescription1"
    t.integer "pqty1"
    t.integer "pdays1"
    t.decimal "ppricing1"
    t.string "pplumbing2"
    t.string "pdescription2"
    t.integer "pqty2"
    t.integer "pdays2"
    t.decimal "ppricing2"
    t.string "pelectical3"
    t.string "pdescription3"
    t.integer "pqty3"
    t.integer "pdays3"
    t.decimal "ppricing3"
    t.string "pderm4"
    t.string "pdescription4"
    t.integer "pqty4"
    t.integer "pdays4"
    t.decimal "ppricing4"
    t.string "ptree5"
    t.string "pdescription5"
    t.integer "pqty5"
    t.integer "pdays5"
    t.decimal "ppricing5"
    t.string "pmechanical6"
    t.string "pdescription6"
    t.integer "pqty6"
    t.integer "pdays6"
    t.decimal "ppricing6"
    t.string "ptotal"
    t.string "mmiscellaneous1"
    t.string "mdescription1"
    t.integer "mqtysfft1"
    t.integer "mdays1"
    t.decimal "mpricing1"
    t.string "mdefault2"
    t.string "mdescription2"
    t.integer "mqtysfft2"
    t.integer "mdays2"
    t.decimal "mpricing2"
    t.string "mdefault3"
    t.string "mdescription3"
    t.integer "mqtysfft3"
    t.integer "mdays3"
    t.decimal "mpricing3"
    t.decimal "mtotal"
    t.decimal "subtotal"
    t.decimal "profit"
    t.decimal "total"
    t.decimal "sf"
    t.decimal "persf"
    t.decimal "totaldays"
    t.decimal "profitporcen"
    t.decimal "salvage"
    t.decimal "atotal"
    t.string "sdefault1"
    t.string "sdescription1"
    t.integer "sqtysflf1"
    t.integer "sdays1"
    t.integer "spricing"
    t.decimal "stotal1"
    t.decimal "stotal"
    t.decimal "ttotal1"
    t.decimal "ttotal2"
    t.decimal "ttotal3"
    t.decimal "ptotal1"
    t.decimal "ptotal2"
    t.decimal "ptotal3"
    t.decimal "ptotal4"
    t.decimal "ptotal5"
    t.decimal "ptotal6"
    t.decimal "mtotal1"
    t.decimal "mtotal2"
    t.decimal "mtotal3"
    t.string "mfill1"
    t.string "mdefault4"
    t.string "mdescription4"
    t.integer "mqtysfft4"
    t.integer "mdays4"
    t.decimal "mpricing4"
    t.decimal "mtotal4"
    t.string "mdefault5"
    t.string "mdescription5"
    t.integer "mqtysfft5"
    t.integer "mdays5"
    t.decimal "mpricing5"
    t.decimal "mtotal5"
    t.string "ttree1"
    t.string "tdescription4"
    t.integer "tqtyyds4"
    t.integer "tdays4"
    t.decimal "tpricing4"
    t.decimal "ttotal4"
    t.string "mdefault6"
    t.string "mdescription6"
    t.integer "mqtysfft6"
    t.integer "mdays6"
    t.decimal "mpricing6"
    t.decimal "mtotal6"
    t.string "mdefault7"
    t.string "mdescription7"
    t.integer "mqtysfft7"
    t.integer "mdays7"
    t.decimal "mpricing7"
    t.decimal "mtotal7"
    t.string "mdefault8"
    t.string "mdescription8"
    t.integer "mqtysfft8"
    t.integer "mdays8"
    t.decimal "mpricing8"
    t.decimal "mtotal8"
    t.string "spricing1"
    t.decimal "pptotal"
    t.date "date1"
    t.string "address"
    t.string "saw1"
    t.decimal "scrap"
    t.decimal "jobcost"
    t.decimal "order1"
    t.decimal "order2"
    t.decimal "order3"
    t.decimal "order4"
    t.decimal "order5"
    t.decimal "tcontract"
    t.decimal "totalcost1"
    t.decimal "tprofit"
    t.decimal "tprofitsalvage"
    t.decimal "pool"
    t.decimal "drivewall"
    t.string "defaultfinal"
    t.decimal "commercial"
    t.decimal "defaultfinaltext"
    t.decimal "concrete"
    t.decimal "trash"
    t.decimal "tloads"
    t.decimal "ydsloads"
    t.decimal "tyards1"
    t.decimal "tyards2"
    t.decimal "ydsf1"
    t.decimal "ydssf2"
    t.decimal "vsa"
    t.decimal "vse"
    t.decimal "vsc"
    t.decimal "vst"
    t.decimal "vsp"
    t.decimal "vsm"
    t.integer "vsx"
    t.string "mhydro9"
    t.string "mdescription9"
    t.integer "mqtysfft9"
    t.integer "mdays9"
    t.decimal "mpricing9"
    t.decimal "mtotal9"
    t.string "mfreon11"
    t.string "mdescription11"
    t.integer "mqtysfft11"
    t.integer "mdays11"
    t.decimal "mpricing11"
    t.decimal "mtotal11"
    t.decimal "atotalvs"
    t.decimal "etotalvs"
    t.decimal "ltotalvs"
    t.decimal "stotalvs"
    t.decimal "ttotalvs"
    t.decimal "ptotalvs"
    t.decimal "mtotalvs"
    t.decimal "totalvs"
    t.string "name"
    t.datetime "date"
    t.string "code"
    t.string "saw2"
    t.string "sdescription2"
    t.integer "sqtysflf2"
    t.integer "sdays2"
    t.decimal "spricing2"
    t.decimal "stotal2"
    t.string "saw3"
    t.string "sdescription3"
    t.integer "sqtysflf3"
    t.integer "sdays3"
    t.decimal "spricing3"
    t.decimal "stotal3"
    t.decimal "invoice"
    t.integer "ahours8"
    t.integer "ahours9"
    t.integer "ahours1"
    t.integer "ahours2"
    t.integer "ahours3"
    t.integer "ahours4"
    t.integer "ahours5"
    t.integer "ahours6"
    t.integer "ahours7"
    t.string "mdescription12"
    t.integer "mqtysfft12"
    t.decimal "mpricing12"
    t.decimal "mtotal12"
    t.string "mdescription13"
    t.integer "mqtysfft13"
    t.decimal "mpricing13"
    t.decimal "mtotal13"
    t.string "mdescription14"
    t.integer "mqtysfft14"
    t.decimal "mpricing14"
    t.decimal "mtotal14"
    t.string "mdescription15"
    t.integer "mqtysfft15"
    t.decimal "mpricing15"
    t.decimal "mtotal15"
    t.decimal "ferrous"
    t.decimal "nonferrous"
    t.decimal "misc"
    t.integer "alabor10"
    t.string "adescription10"
    t.integer "aemp10"
    t.integer "adays10"
    t.integer "ahours10"
    t.decimal "apricing10"
    t.decimal "atotal10"
    t.integer "alabor11"
    t.string "adescription11"
    t.integer "aemp11"
    t.integer "adays11"
    t.integer "ahours11"
    t.decimal "apricing11"
    t.decimal "atotal11"
    t.integer "alabor12"
    t.string "adescription12"
    t.integer "aemp12"
    t.integer "adays12"
    t.integer "ahours12"
    t.decimal "apricing12"
    t.decimal "atotal12"
    t.string "edefault9"
    t.string "edescription9"
    t.integer "eqty9"
    t.integer "edaywk9"
    t.decimal "epricing9"
    t.decimal "etotal9"
    t.string "edefault10"
    t.string "edescription10"
    t.integer "eqty10"
    t.integer "edaywk10"
    t.decimal "epricing10"
    t.decimal "etotal10"
    t.string "edefault11"
    t.string "edescription11"
    t.integer "eqty11"
    t.integer "edaywk11"
    t.decimal "epricing11"
    t.decimal "etotal11"
    t.string "edefault12"
    t.string "edescription12"
    t.integer "eqty12"
    t.integer "edaywk12"
    t.decimal "epricing12"
    t.decimal "etotal12"
    t.integer "over10"
    t.integer "over11"
    t.integer "over12"
    t.string "tdescription5"
    t.integer "tqtysfft5"
    t.decimal "tpricing5"
    t.decimal "ttotal5"
    t.decimal "salvagetotal"
    t.string "tdescription6"
    t.integer "tqtyyds6"
    t.decimal "tpricing6"
    t.decimal "ttotal6"
    t.string "subdefault1"
    t.string "subdescription1"
    t.integer "subqtysfft1"
    t.decimal "subpricing1"
    t.decimal "subtotal1"
    t.string "subdefault2"
    t.string "subdescription2"
    t.integer "subqtysfft2"
    t.decimal "subpricing2"
    t.decimal "subtotal2"
    t.decimal "subtotaltotal"
    t.decimal "vscontractor"
    t.decimal "charge_cost"
    t.decimal "total_charge_cost"
    t.integer "overl"
    t.integer "overo"
    t.integer "overs"
    t.integer "overd"
    t.string "pdescription7"
    t.integer "pqty7"
    t.decimal "ppricing7"
    t.decimal "ptotal7"
    t.decimal "sumco"
    t.decimal "totalover1"
    t.decimal "totalover2"
    t.decimal "totalover3"
    t.decimal "totalover4"
    t.decimal "totaltotalover"
    t.bigint "estimated_id"
    t.string "mdescription16"
    t.integer "mqtysfft16"
    t.decimal "mpricing16"
    t.decimal "mtotal16"
    t.decimal "mpricing21"
    t.string "mdescription17"
    t.integer "mqtysfft17"
    t.decimal "mpricing17"
    t.decimal "mtotal17"
    t.string "subdefault3"
    t.string "subdescription3"
    t.integer "subqtysfft3"
    t.decimal "subpricing3"
    t.decimal "subtotal3"
    t.string "mdescription18"
    t.integer "mqtysfft18"
    t.decimal "mpricing18"
    t.decimal "mtotal18"
    t.string "pmanager"
    t.string "pemail"
    t.bigint "pcell"
    t.string "supervisor"
    t.bigint "scell"
    t.date "sdate"
    t.date "fdate"
    t.integer "noc"
    t.date "nocdate"
    t.date "nocedate"
    t.integer "nto"
    t.date "ntodate"
    t.string "pdescription8"
    t.integer "pqty8"
    t.decimal "ppricing8"
    t.decimal "ptotal8"
    t.decimal "dailyexpenses"
    t.string "fdescription1"
    t.integer "fqtysflf1"
    t.integer "fdays1"
    t.decimal "fpricing1"
    t.decimal "ftotal1"
    t.decimal "ftotal"
    t.string "fuel1"
    t.decimal "ftotalvs"
    t.string "ec_description3"
    t.integer "ec_qty3"
    t.decimal "ec_pricing3"
    t.decimal "ec_total3"
    t.string "ec_description4"
    t.integer "ec_qty4"
    t.decimal "ec_pricing4"
    t.decimal "ec_total4"
    t.string "ec_description5"
    t.integer "ec_qty5"
    t.decimal "ec_pricing5"
    t.decimal "ec_total5"
    t.decimal "ec_total"
    t.decimal "tf_total"
    t.string "mov_pdescription2"
    t.integer "mov_pqty2"
    t.decimal "mov_pricing2"
    t.decimal "mov_total2"
    t.decimal "per_total"
    t.decimal "ec_totalvs"
    t.decimal "tf_totalvs"
    t.decimal "per_totalvs"
    t.string "mdescription31"
    t.integer "mqtysfft31"
    t.decimal "mpricing31"
    t.decimal "mtotal31"
    t.string "mdescription32"
    t.integer "mqtysfft32"
    t.decimal "mpricing32"
    t.decimal "mtotal32"
    t.decimal "eresult1"
    t.decimal "eresult2"
    t.decimal "eresult3"
    t.decimal "eresult4"
    t.decimal "eresult5"
    t.decimal "eresult6"
    t.decimal "eresult7"
    t.decimal "eresult8"
    t.decimal "eresult9"
    t.decimal "eresult10"
    t.decimal "eresult11"
    t.decimal "eresult12"
    t.decimal "totalfuel"
    t.integer "mov_pqty3"
    t.decimal "mov_pricing3"
    t.decimal "mov_total3"
    t.string "mov_pdescription3"
    t.index ["estimated_id"], name: "index_cost_sheets_on_estimated_id"
  end

  create_table "dailylogs", force: :cascade do |t|
    t.string "name_project"
    t.integer "workers"
    t.decimal "hours"
    t.decimal "totalh"
    t.string "location"
    t.string "coments"
    t.string "wather"
    t.string "date1"
    t.string "manpower"
    t.string "equipment"
    t.integer "qtye"
    t.integer "qtyem"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "cname"
    t.string "pname"
    t.datetime "date"
    t.integer "whater"
    t.integer "labor1"
    t.integer "manqty1"
    t.integer "manqty2"
    t.integer "manqty3"
    t.integer "manqty4"
    t.integer "manqty5"
    t.integer "manqty6"
    t.integer "manqty7"
    t.integer "manqty8"
    t.integer "equipqty1"
    t.integer "equipqty2"
    t.integer "equipqty3"
    t.integer "equipqty4"
    t.integer "equipqty5"
    t.integer "equipqty6"
    t.integer "equipqty7"
    t.integer "equipqty8"
    t.integer "mantotal"
    t.integer "equiptotal"
    t.string "remarks"
    t.integer "labor2"
    t.integer "labor3"
    t.integer "labor4"
    t.string "labor5"
    t.string "labor6"
    t.string "labor7"
    t.integer "equip1"
    t.integer "equip2"
    t.integer "equip3"
    t.integer "equip4"
    t.integer "equip5"
    t.integer "equip6"
    t.integer "equip7"
    t.integer "equip8"
    t.integer "labor9"
    t.integer "equip9"
    t.integer "hour1"
    t.integer "hour2"
    t.integer "hour3"
    t.integer "hour4"
    t.integer "hour5"
    t.integer "hour6"
    t.integer "hour7"
    t.integer "thours"
    t.integer "report"
    t.integer "concrete"
    t.integer "asphalt"
    t.integer "fill"
    t.integer "trash"
    t.bigint "cost_sheet_id"
    t.integer "daily_number", default: 1
    t.decimal "pconcrete"
    t.decimal "pasphalt"
    t.decimal "pfill"
    t.decimal "pvegitation"
    t.decimal "ptrash"
    t.string "dconcrete"
    t.string "dasphalt"
    t.string "dfill"
    t.string "dvegitation"
    t.string "dtrash"
    t.string "comments"
    t.integer "vegitation"
    t.decimal "aasphalt"
    t.decimal "afill"
    t.decimal "avegitation"
    t.decimal "atrash"
    t.decimal "aconcrete"
    t.decimal "tconcrete"
    t.decimal "tasphalt"
    t.decimal "tfill"
    t.decimal "tvegetation"
    t.decimal "ttrash"
    t.string "avatar"
    t.integer "labor8"
    t.integer "hour8"
    t.integer "manqty9"
    t.integer "hour9"
    t.integer "equipqty9"
    t.integer "labor10"
    t.integer "manqty10"
    t.integer "hour10"
    t.integer "equip10"
    t.integer "equipqty10"
    t.integer "labor11"
    t.integer "manqty11"
    t.integer "hour11"
    t.integer "equip11"
    t.integer "equipqty11"
    t.integer "labor12"
    t.integer "manqty12"
    t.integer "hour12"
    t.integer "equip12"
    t.integer "equipqty12"
    t.integer "labor100"
    t.integer "alabor1"
    t.integer "alabor2"
    t.integer "alabor3"
    t.integer "alabor4"
    t.integer "alabor5"
    t.integer "alabor6"
    t.integer "alabor7"
    t.integer "alabor8"
    t.integer "alabor9"
    t.integer "alabor10"
    t.integer "alabor11"
    t.integer "alabor12"
    t.string "ctickets1", default: [], array: true
    t.string "ctransporter1"
    t.integer "ctruck1"
    t.string "ctickets2", default: [], array: true
    t.string "ctransporter2"
    t.integer "ctruck2"
    t.string "ctickets3", default: [], array: true
    t.string "ctransporter3"
    t.integer "ctruck3"
    t.string "ctransporter4"
    t.string "atransporter1"
    t.string "atransporter2"
    t.string "ftransporter1"
    t.string "ftransporter2"
    t.string "vtransporter1"
    t.string "vtransporter2"
    t.string "ttransporter1"
    t.string "ttransporter2"
    t.integer "aqty1"
    t.decimal "apricing1"
    t.decimal "atotal1"
    t.string "aqty2"
    t.string "apricing2"
    t.string "atotal2"
    t.string "cqty1"
    t.string "cpricing1"
    t.string "ctotal1"
    t.string "cqty2"
    t.string "cpricing2"
    t.string "ctotal2"
    t.string "cqty3"
    t.string "cpricing3"
    t.string "ctotal3"
    t.string "cqty4"
    t.string "cpricing4"
    t.string "ctotal4"
    t.string "fqty1"
    t.string "fpricing1"
    t.string "ftotal1"
    t.string "fqty2"
    t.string "fpricing2"
    t.string "ftotal2"
    t.string "vqty1"
    t.string "vpricing1"
    t.string "vtotal1"
    t.string "vqty2"
    t.string "vpricing2"
    t.string "vtotal2"
    t.string "tqty1"
    t.string "tpricing1"
    t.string "ttotal1"
    t.string "tqty2"
    t.string "tpricing2"
    t.string "ttotal2"
    t.integer "omanqty1"
    t.integer "ohour1"
    t.integer "smanqty1"
    t.integer "shour1"
    t.integer "dmanqty1"
    t.integer "dhour1"
    t.integer "totallqty"
    t.integer "totaloqty"
    t.integer "totalsqty"
    t.integer "totaldqty"
    t.integer "totalhoursl"
    t.integer "totalhourso"
    t.integer "totalhourss"
    t.integer "totalhoursd"
    t.integer "omanqty2"
    t.integer "ohour2"
    t.integer "smanqty2"
    t.integer "shour2"
    t.integer "dmanqty2"
    t.integer "dhour2"
    t.integer "omanqty3"
    t.integer "ohour3"
    t.integer "smanqty3"
    t.integer "shour3"
    t.integer "dmanqty3"
    t.integer "dhour3"
    t.integer "omanqty4"
    t.integer "ohour4"
    t.integer "smanqty4"
    t.integer "shour4"
    t.integer "dmanqty4"
    t.integer "dhour4"
    t.integer "omanqty5"
    t.integer "ohour5"
    t.integer "smanqty5"
    t.integer "shour5"
    t.integer "dmanqty5"
    t.integer "dhour5"
    t.integer "omanqty6"
    t.integer "ohour6"
    t.integer "smanqty6"
    t.integer "shour6"
    t.integer "dmanqty6"
    t.integer "dhour6"
    t.string "atransporter3"
    t.integer "aqty3"
    t.decimal "apricing3"
    t.decimal "atotal3"
    t.string "atransporter4"
    t.integer "aqty4"
    t.decimal "apricing4"
    t.decimal "atotal4"
    t.string "ftransporter3"
    t.integer "fqty3"
    t.decimal "fpricing3"
    t.decimal "ftotal3"
    t.string "ftransporter4"
    t.integer "fqty4"
    t.decimal "fpricing4"
    t.decimal "ftotal4"
    t.string "vtransporter3"
    t.integer "vqty3"
    t.decimal "vpricing3"
    t.decimal "vtotal3"
    t.string "vtransporter4"
    t.integer "vqty4"
    t.decimal "vpricing4"
    t.decimal "vtotal4"
    t.string "ttransporter3"
    t.integer "tqty3"
    t.decimal "tpricing3"
    t.decimal "ttotal3"
    t.string "ttransporter4"
    t.integer "tqty4"
    t.decimal "tpricing4"
    t.decimal "ttotal4"
    t.string "rtransporter1"
    t.integer "rqty1"
    t.decimal "rpricing1"
    t.decimal "rtotal1"
    t.string "rtransporter2"
    t.integer "rqty2"
    t.decimal "rpricing2"
    t.decimal "rtotal2"
    t.string "rtransporter3"
    t.integer "rqty3"
    t.decimal "rpricing3"
    t.decimal "rtotal3"
    t.string "rtransporter4"
    t.integer "rqty4"
    t.decimal "rpricing4"
    t.decimal "rtotal4"
    t.decimal "trock"
    t.integer "rock"
    t.decimal "prock"
    t.decimal "apricing20"
    t.decimal "cpricing20"
    t.decimal "cpricing30"
    t.decimal "cpricing40"
    t.decimal "fpricing10"
    t.decimal "fpricing20"
    t.decimal "vpricing10"
    t.decimal "vpricing20"
    t.decimal "tpricing10"
    t.decimal "tpricing20"
    t.decimal "atotal20"
    t.decimal "ctotal10"
    t.decimal "ctotal20"
    t.decimal "ctotal30"
    t.decimal "ctotal40"
    t.decimal "ftotal10"
    t.decimal "ftotal20"
    t.decimal "vtotal10"
    t.decimal "vtotal20"
    t.decimal "ttotal10"
    t.decimal "ttotal20"
    t.string "xtransporter1"
    t.integer "xqty1"
    t.decimal "xpricing1"
    t.decimal "xtotal10"
    t.string "xtransporter2"
    t.integer "xqty2"
    t.decimal "xpricing2"
    t.decimal "xtotal20"
    t.string "xtransporter3"
    t.integer "xqty3"
    t.decimal "xpricing3"
    t.decimal "xtotal30"
    t.string "xtransporter4"
    t.integer "xqty4"
    t.decimal "xpricing4"
    t.decimal "xtotal40"
    t.decimal "trebar"
    t.integer "rebar"
    t.decimal "prebar"
    t.integer "overl"
    t.integer "overo"
    t.integer "overs"
    t.integer "overd"
    t.integer "omanqty7"
    t.integer "omanqty8"
    t.integer "omanqty9"
    t.integer "omanqty10"
    t.integer "omanqty11"
    t.integer "omanqty12"
    t.integer "ohour7"
    t.integer "ohour8"
    t.integer "ohour9"
    t.integer "ohour10"
    t.integer "ohour11"
    t.integer "ohour12"
    t.integer "smanqty7"
    t.integer "smanqty8"
    t.integer "smanqty9"
    t.integer "smanqty10"
    t.integer "smanqty11"
    t.integer "smanqty12"
    t.integer "shour7"
    t.integer "shour8"
    t.integer "shour9"
    t.integer "shour10"
    t.integer "shour11"
    t.integer "shour12"
    t.integer "dmanqty7"
    t.integer "dmanqty8"
    t.integer "dmanqty9"
    t.integer "dmanqty10"
    t.integer "dmanqty11"
    t.integer "dmanqty12"
    t.integer "dhour7"
    t.integer "dhour8"
    t.integer "dhour9"
    t.integer "dhour10"
    t.integer "dhour11"
    t.integer "dhour12"
    t.string "mtransporter1"
    t.string "mtransporter2"
    t.string "mtransporter3"
    t.string "mtransporter4"
    t.string "mtransporter5"
    t.string "mtransporter6"
    t.decimal "mtotal1"
    t.decimal "mtotal2"
    t.decimal "mtotal3"
    t.decimal "mtotal4"
    t.decimal "mtotal5"
    t.decimal "mtotal6"
    t.decimal "pmisellaneous"
    t.decimal "mpricing1"
    t.decimal "mpricing2"
    t.decimal "mpricing3"
    t.decimal "mpricing4"
    t.decimal "mpricing5"
    t.decimal "mpricing6"
    t.decimal "fuel"
    t.index ["cost_sheet_id"], name: "index_dailylogs_on_cost_sheet_id"
  end

  create_table "employees", force: :cascade do |t|
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "name"
    t.string "lastname"
    t.string "phone"
    t.string "active"
    t.bigint "cost_sheet_id"
    t.integer "function"
    t.integer "project"
    t.integer "active1"
    t.index ["cost_sheet_id"], name: "index_employees_on_cost_sheet_id"
  end

  create_table "estimateds", force: :cascade do |t|
    t.string "name"
    t.integer "status"
    t.string "date"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "alabor1"
    t.string "adescription1"
    t.integer "adays1"
    t.integer "aemp1"
    t.decimal "apricing1", precision: 8, scale: 2
    t.decimal "atotal1", precision: 8, scale: 2
    t.integer "alabor2"
    t.string "adescription2"
    t.integer "adays2"
    t.integer "aemp2"
    t.decimal "apricing2", precision: 8, scale: 2
    t.decimal "atotal2", precision: 8, scale: 2
    t.integer "alabor3"
    t.string "adescriptio3"
    t.integer "adays3"
    t.integer "aemp3"
    t.decimal "apricing3", precision: 8, scale: 2
    t.decimal "atotal3", precision: 8, scale: 2
    t.integer "alabor4"
    t.string "adescription4"
    t.integer "adays4"
    t.integer "aemp4"
    t.decimal "apricing4", precision: 8, scale: 2
    t.decimal "atotal4", precision: 8, scale: 2
    t.integer "alabor5"
    t.string "adescription5"
    t.integer "adays5"
    t.integer "aemp5"
    t.decimal "apricing5", precision: 8, scale: 2
    t.decimal "atotal5", precision: 8, scale: 2
    t.integer "alabor6"
    t.string "adescription6"
    t.integer "adays6"
    t.integer "aemp6"
    t.decimal "apricing6", precision: 8, scale: 2
    t.decimal "atotal6", precision: 8, scale: 2
    t.integer "alabor7"
    t.string "adescription7"
    t.integer "adays7"
    t.integer "aemp7"
    t.decimal "apricing7", precision: 8, scale: 2
    t.decimal "atotal7", precision: 8, scale: 2
    t.integer "alabor8"
    t.string "adescription8"
    t.integer "adays8"
    t.integer "aemp8"
    t.decimal "apricing8", precision: 8, scale: 2
    t.decimal "atotal8", precision: 8, scale: 2
    t.integer "alabor9"
    t.string "adescription9"
    t.integer "adays9"
    t.integer "aemp9"
    t.decimal "apricing9", precision: 8, scale: 2
    t.decimal "atotal9", precision: 8, scale: 2
    t.string "eexcavator1"
    t.string "edescription1"
    t.integer "eqty1"
    t.integer "edaywk1"
    t.decimal "epricing1", precision: 8, scale: 2
    t.decimal "etotal1", precision: 10, scale: 2
    t.string "eexcavator2"
    t.string "edescription2"
    t.integer "eqty2"
    t.integer "edaywk2"
    t.decimal "epricing2", precision: 8, scale: 2
    t.decimal "etotal2", precision: 10, scale: 2
    t.string "scisso3"
    t.string "edescription3"
    t.integer "eqty3"
    t.integer "edaywk3"
    t.decimal "epricing3", precision: 8, scale: 2
    t.decimal "etotal3", precision: 10, scale: 2
    t.string "loader4"
    t.string "edescription4"
    t.integer "eqty4"
    t.integer "edaywk4"
    t.decimal "epricing4", precision: 8, scale: 2
    t.decimal "etotal4", precision: 10, scale: 2
    t.string "etrunck5"
    t.string "edescription5"
    t.integer "eqty5"
    t.integer "edaywk5"
    t.decimal "epricing5", precision: 8, scale: 2
    t.decimal "etotal5", precision: 10, scale: 2
    t.string "ebobcat6"
    t.string "edescription6"
    t.integer "eqty6"
    t.integer "edaywk6"
    t.decimal "epricing6", precision: 8, scale: 2
    t.decimal "etotal6", precision: 10, scale: 2
    t.decimal "etotal", precision: 10, scale: 2
    t.string "edefault7"
    t.string "edescription7"
    t.integer "eqty7"
    t.integer "edaywk7"
    t.decimal "epricing7", precision: 8, scale: 2
    t.decimal "etotal7", precision: 10, scale: 2
    t.string "edefault8"
    t.string "edescription8"
    t.integer "eqty8"
    t.integer "edaywk8"
    t.decimal "epricing8", precision: 8, scale: 2
    t.decimal "etotal8", precision: 10, scale: 2
    t.string "ttrash1"
    t.string "tdescription1"
    t.integer "tqtyyds1"
    t.integer "tdays1"
    t.decimal "tpricing1", precision: 8, scale: 2
    t.string "tconcrete2"
    t.string "tdescription2"
    t.integer "tqtyyds2"
    t.integer "tdays2"
    t.decimal "tpricing2", precision: 8, scale: 2
    t.string "tasphalt3"
    t.string "tdescription3"
    t.integer "tqtyyds3"
    t.integer "tdays3"
    t.decimal "tpricing3", precision: 8, scale: 2
    t.decimal "ttotal", precision: 10, scale: 2
    t.string "pdemo1"
    t.string "pdescription1"
    t.integer "pqty1"
    t.integer "pdays1"
    t.decimal "ppricing1", precision: 8, scale: 2
    t.string "pplumbing2"
    t.string "pdescription2"
    t.integer "pqty2"
    t.integer "pdays2"
    t.decimal "ppricing2", precision: 8, scale: 2
    t.string "pelectical3"
    t.string "pdescription3"
    t.integer "pqty3"
    t.integer "pdays3"
    t.decimal "ppricing3", precision: 8, scale: 2
    t.string "pderm4"
    t.string "pdescription4"
    t.integer "pqty4"
    t.integer "pdays4"
    t.decimal "ppricing4", precision: 8, scale: 2
    t.string "ptree5"
    t.string "pdescription5"
    t.integer "pqty5"
    t.integer "pdays5"
    t.decimal "ppricing5", precision: 8, scale: 2
    t.string "pmechanical6"
    t.string "pdescription6"
    t.integer "pqty6"
    t.integer "pdays6"
    t.decimal "ppricing6", precision: 8, scale: 2
    t.string "ptotal"
    t.string "mmiscellaneous1"
    t.string "mdescription1"
    t.integer "mqtysfft1"
    t.integer "mdays1"
    t.decimal "mpricing1", precision: 8, scale: 2
    t.string "mdefault2"
    t.string "mdescription2"
    t.integer "mqtysfft2"
    t.integer "mdays2"
    t.decimal "mpricing2", precision: 8, scale: 2
    t.string "mdefault3"
    t.string "mdescription3"
    t.integer "mqtysfft3"
    t.integer "mdays3"
    t.decimal "mpricing3", precision: 8, scale: 2
    t.decimal "mtotal", precision: 10, scale: 2
    t.decimal "subtotal", precision: 10, scale: 2
    t.decimal "profit", precision: 10, scale: 2
    t.decimal "total", precision: 10, scale: 2
    t.decimal "sf", precision: 10, scale: 2
    t.decimal "persf", precision: 10, scale: 2
    t.integer "totaldays"
    t.decimal "profitporcen", precision: 10, scale: 2
    t.integer "salvage"
    t.decimal "atotal", precision: 10, scale: 2
    t.string "sdefault1"
    t.string "sdescription1"
    t.integer "sqtysflf1"
    t.integer "sdays1"
    t.decimal "spricing", precision: 8, scale: 2
    t.decimal "stotal1", precision: 10, scale: 2
    t.decimal "stotal", precision: 10, scale: 2
    t.decimal "ttotal1", precision: 10, scale: 2
    t.decimal "ttotal2", precision: 10, scale: 2
    t.decimal "ttotal3", precision: 10, scale: 2
    t.decimal "ptotal1", precision: 10, scale: 2
    t.decimal "ptotal2", precision: 10, scale: 2
    t.decimal "ptotal3", precision: 10, scale: 2
    t.decimal "ptotal4", precision: 10, scale: 2
    t.decimal "ptotal5", precision: 10, scale: 2
    t.decimal "ptotal6", precision: 10, scale: 2
    t.decimal "mtotal1", precision: 10, scale: 2
    t.decimal "mtotal2", precision: 10, scale: 2
    t.decimal "mtotal3", precision: 10, scale: 2
    t.string "mfill1"
    t.string "mdefault4"
    t.string "mdescription4"
    t.integer "mqtysfft4"
    t.integer "mdays4"
    t.decimal "mpricing4", precision: 8, scale: 2
    t.decimal "mtotal4", precision: 10, scale: 2
    t.string "mdefault5"
    t.string "mdescription5"
    t.integer "mqtysfft5"
    t.integer "mdays5"
    t.decimal "mpricing5", precision: 8, scale: 2
    t.decimal "mtotal5", precision: 10, scale: 2
    t.string "ttree1"
    t.string "tdescription4"
    t.integer "tqtyyds4"
    t.integer "tdays4"
    t.decimal "tpricing4", precision: 8, scale: 2
    t.decimal "ttotal4", precision: 10, scale: 2
    t.string "mdefault6"
    t.string "mdescription6"
    t.integer "mqtysfft6"
    t.integer "mdays6"
    t.decimal "mpricing6", precision: 8, scale: 2
    t.decimal "mtotal6", precision: 10, scale: 2
    t.string "mdefault7"
    t.string "mdescription7"
    t.integer "mqtysfft7"
    t.integer "mdays7"
    t.decimal "mpricing7", precision: 8, scale: 2
    t.decimal "mtotal7", precision: 10, scale: 2
    t.string "mdefault8"
    t.string "mdescription8"
    t.integer "mqtysfft8"
    t.integer "mdays8"
    t.decimal "mpricing8", precision: 8, scale: 2
    t.decimal "mtotal8", precision: 10, scale: 2
    t.string "spricing1"
    t.decimal "pptotal", precision: 10, scale: 2
    t.date "date1"
    t.string "address"
    t.string "saw1"
    t.integer "cost_sheet_id"
    t.string "mhydro9"
    t.string "mdescription9"
    t.integer "mqtysfft9"
    t.integer "mdays9"
    t.decimal "mpricing9"
    t.decimal "mtotal9", precision: 10, scale: 2
    t.string "mfence10"
    t.string "mdescription10"
    t.integer "mqtysfft10"
    t.integer "mdays10"
    t.decimal "mpricing10"
    t.decimal "mtotal10", precision: 10, scale: 2
    t.string "mfreon11"
    t.string "mdescription11"
    t.integer "mqtysfft11"
    t.integer "mdays11"
    t.decimal "mpricing11"
    t.decimal "mtotal11", precision: 10, scale: 2
    t.decimal "invoice"
    t.string "saw2"
    t.string "sdescription2"
    t.integer "sqtysflf2"
    t.integer "sdays2"
    t.decimal "spricing2"
    t.decimal "stotal2", precision: 10, scale: 2
    t.string "saw3"
    t.string "sdescription3"
    t.integer "sqtysflf3"
    t.integer "sdays3"
    t.decimal "spricing3"
    t.decimal "stotal3", precision: 10, scale: 2
    t.integer "ahours1"
    t.integer "ahours2"
    t.integer "ahours3"
    t.integer "ahours4"
    t.integer "ahours5"
    t.integer "ahours6"
    t.integer "ahours7"
    t.integer "ahours8"
    t.integer "ahours9"
    t.decimal "ttotalx", precision: 10, scale: 2
    t.integer "over1"
    t.integer "over2"
    t.integer "over3"
    t.integer "over4"
    t.integer "over5"
    t.integer "over6"
    t.integer "over7"
    t.integer "over8"
    t.integer "over9"
    t.string "mdescription12"
    t.integer "mqtysfft12"
    t.decimal "mpricing12"
    t.decimal "mtotal12", precision: 10, scale: 2
    t.string "mdescription13"
    t.integer "mqtysfft13"
    t.decimal "mpricing13"
    t.decimal "mtotal13", precision: 10, scale: 2
    t.string "mdescription14"
    t.integer "mqtysfft14"
    t.decimal "mpricing14"
    t.decimal "mtotal14", precision: 10, scale: 2
    t.string "mdescription15"
    t.integer "mqtysfft15"
    t.decimal "mpricing15"
    t.decimal "mtotal15", precision: 10, scale: 2
    t.decimal "totalsalvage"
    t.string "user"
    t.integer "alabor10"
    t.string "adescription10"
    t.integer "aemp10"
    t.integer "adays10"
    t.integer "ahours10"
    t.decimal "apricing10"
    t.decimal "atotal10"
    t.integer "alabor11"
    t.string "adescription11"
    t.integer "aemp11"
    t.integer "adays11"
    t.integer "ahours11"
    t.decimal "apricing11"
    t.decimal "atotal11"
    t.integer "alabor12"
    t.string "adescription12"
    t.integer "aemp12"
    t.integer "adays12"
    t.integer "ahours12"
    t.decimal "apricing12"
    t.decimal "atotal12"
    t.string "edefault9"
    t.string "edescription9"
    t.integer "eqty9"
    t.integer "edaywk9"
    t.decimal "epricing9"
    t.decimal "etotal9", precision: 10, scale: 2
    t.string "edefault10"
    t.string "edescription10"
    t.integer "eqty10"
    t.integer "edaywk10"
    t.decimal "epricing10"
    t.decimal "etotal10", precision: 10, scale: 2
    t.string "edefault11"
    t.string "edescription11"
    t.integer "eqty11"
    t.integer "edaywk11"
    t.decimal "epricing11"
    t.decimal "etotal11", precision: 10, scale: 2
    t.string "edefault12"
    t.string "edescription12"
    t.integer "eqty12"
    t.integer "edaywk12"
    t.decimal "epricing12"
    t.decimal "etotal12", precision: 10, scale: 2
    t.integer "over10"
    t.integer "over11"
    t.integer "over12"
    t.string "tdescription5"
    t.integer "tqtysfft5"
    t.decimal "tpricing5"
    t.decimal "ttotal5", precision: 10, scale: 2
    t.string "tdescription6"
    t.integer "tqtyyds6"
    t.decimal "tpricing6"
    t.decimal "ttotal6", precision: 10, scale: 2
    t.string "subdefault1"
    t.string "subdescription1"
    t.integer "subqtysfft1"
    t.decimal "subpricing1"
    t.decimal "subtotal1"
    t.string "subdefault2"
    t.string "subdescription2"
    t.integer "subqtysfft2"
    t.decimal "subpricing2"
    t.decimal "subtotal2"
    t.decimal "subtotaltotal"
    t.string "pdescription7"
    t.integer "pqty7"
    t.decimal "ppricing7"
    t.decimal "ptotal7", precision: 10, scale: 2
    t.string "mdescription16"
    t.integer "mqtysfft16"
    t.decimal "mpricing16"
    t.decimal "mtotal16", precision: 10, scale: 2
    t.decimal "mpricing21"
    t.string "mdescription17"
    t.integer "mqtysfft17"
    t.decimal "mpricing17"
    t.decimal "mtotal17", precision: 10, scale: 2
    t.string "subdefault3"
    t.string "subdescription3"
    t.integer "subqtysfft3"
    t.decimal "subpricing3"
    t.integer "subporce3"
    t.decimal "subtotal3"
    t.decimal "subporce2"
    t.integer "subporce1"
    t.string "mdescription18"
    t.integer "mqtysfft18"
    t.decimal "mpricing18"
    t.decimal "mtotal18", precision: 10, scale: 2
    t.string "pdescription8"
    t.integer "pqty8"
    t.decimal "ppricing8"
    t.decimal "ptotal8"
    t.string "fdescription1"
    t.integer "fqtysflf1"
    t.integer "fdays1"
    t.decimal "fpricing1"
    t.decimal "ftotal1"
    t.decimal "ftotal"
    t.string "fuel1"
    t.string "ec_description3"
    t.integer "ec_qty3"
    t.decimal "ec_pricing3"
    t.decimal "ec_total3"
    t.string "ec_description4"
    t.integer "ec_qty4"
    t.decimal "ec_pricing4"
    t.decimal "ec_total4"
    t.string "ec_description5"
    t.integer "ec_qty5"
    t.decimal "ec_pricing5"
    t.decimal "ec_total5"
    t.decimal "ec_total"
    t.decimal "tf_total"
    t.string "mov_pdescription2"
    t.integer "mov_pqty2"
    t.decimal "mov_pricing2"
    t.decimal "mov_total2"
    t.decimal "per_total"
    t.string "test10"
    t.string "test"
    t.string "mdescription31"
    t.integer "mqtysfft31"
    t.decimal "mpricing31"
    t.decimal "mtotal31"
    t.string "mdescription32"
    t.integer "mqtysfft32"
    t.decimal "mpricing32"
    t.decimal "mtotal32"
    t.decimal "eresult1"
    t.decimal "eresult2"
    t.decimal "eresult3"
    t.decimal "eresult4"
    t.decimal "eresult5"
    t.decimal "eresult6"
    t.decimal "eresult7"
    t.decimal "eresult8"
    t.decimal "eresult9"
    t.decimal "eresult10"
    t.decimal "eresult11"
    t.decimal "eresult12"
    t.decimal "totalfuel"
    t.integer "mov_pqty3"
    t.decimal "mov_pricing3"
    t.decimal "mov_total3"
    t.string "mov_pdescription3"
  end

  create_table "fill_formulas", force: :cascade do |t|
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "leeds", force: :cascade do |t|
    t.date "date"
    t.string "project"
    t.decimal "tconswaste"
    t.decimal "tdivewaste"
    t.decimal "porcen"
    t.decimal "tlandwaste"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.decimal "method1"
    t.decimal "method2"
    t.decimal "method3"
    t.decimal "method4"
    t.decimal "method5"
    t.decimal "method6"
    t.decimal "method7"
    t.decimal "method8"
    t.decimal "method9"
    t.decimal "method10"
    t.decimal "method11"
    t.decimal "method12"
    t.decimal "method13"
    t.decimal "method14"
    t.decimal "method15"
    t.decimal "method16"
    t.decimal "method17"
    t.decimal "landfill1"
    t.decimal "landfill2"
    t.decimal "landfill3"
    t.decimal "landfill4"
    t.decimal "landfill5"
    t.decimal "landfill6"
    t.decimal "landfill7"
    t.decimal "landfill8"
    t.decimal "landfill9"
    t.decimal "landfill10"
    t.decimal "landfill11"
    t.decimal "landfill12"
    t.decimal "landfill13"
    t.decimal "landfill14"
    t.decimal "landfill15"
    t.decimal "landfill16"
    t.decimal "landfill17"
    t.decimal "recycled1"
    t.decimal "recycled2"
    t.decimal "recycled3"
    t.decimal "recycled4"
    t.decimal "recycled5"
    t.decimal "recycled6"
    t.decimal "recycled7"
    t.decimal "recycled8"
    t.decimal "recycled9"
    t.decimal "recycled10"
    t.decimal "recycled11"
    t.decimal "recycled12"
    t.decimal "recycled13"
    t.decimal "recycled14"
    t.decimal "recycled15"
    t.decimal "recycled16"
    t.decimal "recycled17"
    t.decimal "salvage1"
    t.decimal "salvage2"
    t.decimal "salvage3"
    t.decimal "salvage4"
    t.decimal "salvage5"
    t.decimal "salvage6"
    t.decimal "salvage7"
    t.decimal "salvage8"
    t.decimal "salvage9"
    t.decimal "salvage10"
    t.decimal "salvage11"
    t.decimal "salvage12"
    t.decimal "salvage13"
    t.decimal "salvage14"
    t.decimal "salvage15"
    t.decimal "salvage16"
    t.decimal "salvage17"
    t.decimal "reused1"
    t.decimal "reused2"
    t.decimal "reused3"
    t.decimal "reused4"
    t.decimal "reused5"
    t.decimal "reused6"
    t.decimal "reused7"
    t.decimal "reused8"
    t.decimal "reused9"
    t.decimal "reused10"
    t.decimal "reused11"
    t.decimal "reused12"
    t.decimal "reused13"
    t.decimal "reused14"
    t.decimal "reused15"
    t.decimal "reused16"
    t.decimal "reused17"
    t.decimal "total1"
    t.decimal "total2"
    t.decimal "total3"
    t.decimal "total4"
    t.decimal "total5"
    t.decimal "total6"
    t.decimal "total7"
    t.decimal "total8"
    t.decimal "total9"
    t.decimal "total10"
    t.decimal "total11"
    t.decimal "total12"
    t.decimal "total13"
    t.decimal "total14"
    t.decimal "total15"
    t.decimal "total16"
    t.decimal "total17"
    t.decimal "landfill18"
    t.decimal "recycled18"
    t.decimal "salvage18"
    t.decimal "reused18"
    t.decimal "total18"
    t.string "method18"
    t.decimal "landfill19"
    t.decimal "recycled19"
    t.decimal "salvage19"
    t.decimal "reused19"
    t.decimal "total19"
    t.string "method19"
  end

  create_table "rfis", force: :cascade do |t|
    t.string "pname"
    t.string "location"
    t.string "number"
    t.date "date"
    t.string "pid"
    t.string "drawing"
    t.string "overview"
    t.string "referenced"
    t.integer "nochange1"
    t.integer "nochange2"
    t.decimal "increase_cost"
    t.integer "increase_time"
    t.decimal "decrease_cost"
    t.integer "decrease_time"
    t.string "request"
    t.string "name_request"
    t.string "signature1"
    t.string "signature2"
    t.string "response"
    t.date "date2"
    t.integer "status"
    t.string "name_responding"
    t.string "cname"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "select1"
    t.integer "select2"
    t.integer "select3"
    t.integer "select4"
    t.integer "select5"
    t.integer "select6"
    t.bigint "estimateds_id"
    t.index ["estimateds_id"], name: "index_rfis_on_estimateds_id"
  end

  create_table "rois", force: :cascade do |t|
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "template_uploads", force: :cascade do |t|
    t.string "avatar"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "time_sheets", force: :cascade do |t|
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "address"
    t.date "week"
    t.decimal "mon"
    t.decimal "tue"
    t.decimal "wed"
    t.decimal "thr"
    t.decimal "fri"
    t.decimal "sat"
    t.decimal "sun"
    t.bigint "employee_id"
    t.string "employee_0"
    t.string "employee_1"
    t.string "total_0"
    t.string "total_1"
    t.string "totaltotal"
    t.decimal "employee_2"
    t.decimal "mon_2"
    t.decimal "tue_2"
    t.decimal "wed_2"
    t.decimal "thr_2"
    t.decimal "fri_2"
    t.decimal "sat_2"
    t.decimal "sun_2"
    t.decimal "total_2"
    t.decimal "employee_3"
    t.decimal "mon_3"
    t.decimal "tue_3"
    t.decimal "wed_3"
    t.decimal "thr_3"
    t.decimal "fri_3"
    t.decimal "sat_3"
    t.decimal "sun_3"
    t.decimal "total_3"
    t.decimal "employee_4"
    t.decimal "mon_4"
    t.decimal "tue_4"
    t.decimal "wed_4"
    t.decimal "thr_4"
    t.decimal "fri_4"
    t.decimal "sat_4"
    t.decimal "sun_4"
    t.decimal "total_4"
    t.decimal "employee_5"
    t.decimal "mon_5"
    t.decimal "tue_5"
    t.decimal "wed_5"
    t.decimal "thr_5"
    t.decimal "fri_5"
    t.decimal "sat_5"
    t.decimal "sun_5"
    t.decimal "total_5"
    t.decimal "employee_6"
    t.decimal "mon_6"
    t.decimal "tue_6"
    t.decimal "wed_6"
    t.decimal "thr_6"
    t.decimal "fri_6"
    t.decimal "sat_6"
    t.decimal "sun_6"
    t.decimal "total_6"
    t.decimal "employee_7"
    t.decimal "mon_7"
    t.decimal "tue_7"
    t.decimal "wed_7"
    t.decimal "thr_7"
    t.decimal "fri_7"
    t.decimal "sat_7"
    t.decimal "sun_7"
    t.decimal "total_7"
    t.decimal "employee_8"
    t.decimal "mon_8"
    t.decimal "tue_8"
    t.decimal "wed_8"
    t.decimal "thr_8"
    t.decimal "fri_8"
    t.decimal "sat_8"
    t.decimal "sun_8"
    t.decimal "total_8"
    t.decimal "employee_9"
    t.decimal "mon_9"
    t.decimal "tue_9"
    t.decimal "wed_9"
    t.decimal "thr_9"
    t.decimal "fri_9"
    t.decimal "sat_9"
    t.decimal "sun_9"
    t.decimal "total_9"
    t.decimal "employee_10"
    t.decimal "mon_10"
    t.decimal "tue_10"
    t.decimal "wed_10"
    t.decimal "thr_10"
    t.decimal "fri_10"
    t.decimal "sat_10"
    t.decimal "sun_10"
    t.decimal "total_10"
    t.decimal "employee_11"
    t.decimal "mon_11"
    t.decimal "tue_11"
    t.decimal "wed_11"
    t.decimal "thr_11"
    t.decimal "fri_11"
    t.decimal "sat_11"
    t.decimal "sun_11"
    t.decimal "total_11"
    t.decimal "employee_12"
    t.decimal "mon_12"
    t.decimal "tue_12"
    t.decimal "wed_12"
    t.decimal "thr_12"
    t.decimal "fri_12"
    t.decimal "sat_12"
    t.decimal "sun_12"
    t.decimal "total_12"
    t.decimal "employee_13"
    t.decimal "mon_13"
    t.decimal "tue_13"
    t.decimal "wed_13"
    t.decimal "thr_13"
    t.decimal "fri_13"
    t.decimal "sat_13"
    t.decimal "sun_13"
    t.decimal "total_13"
    t.decimal "employee_14"
    t.decimal "mon_14"
    t.decimal "tue_14"
    t.decimal "wed_14"
    t.decimal "thr_14"
    t.decimal "fri_14"
    t.decimal "sat_14"
    t.decimal "sun_14"
    t.decimal "total_14"
    t.decimal "employee_15"
    t.decimal "mon_15"
    t.decimal "tue_15"
    t.decimal "wed_15"
    t.decimal "thr_15"
    t.decimal "fri_15"
    t.decimal "sat_15"
    t.decimal "sun_15"
    t.decimal "total_15"
    t.decimal "employee_16"
    t.decimal "mon_16"
    t.decimal "tue_16"
    t.decimal "wed_16"
    t.decimal "thr_16"
    t.decimal "fri_16"
    t.decimal "sat_16"
    t.decimal "sun_16"
    t.decimal "total_16"
    t.decimal "employee_17"
    t.decimal "mon_17"
    t.decimal "tue_17"
    t.decimal "wed_17"
    t.decimal "thr_17"
    t.decimal "fri_17"
    t.decimal "sat_17"
    t.decimal "sun_17"
    t.decimal "total_17"
    t.decimal "employee_18"
    t.decimal "mon_18"
    t.decimal "tue_18"
    t.decimal "wed_18"
    t.decimal "thr_18"
    t.decimal "fri_18"
    t.decimal "sat_18"
    t.decimal "sun_18"
    t.decimal "total_18"
    t.decimal "employee_19"
    t.decimal "mon_19"
    t.decimal "tue_19"
    t.decimal "wed_19"
    t.decimal "thr_19"
    t.decimal "fri_19"
    t.decimal "sat_19"
    t.decimal "sun_19"
    t.decimal "total_19"
    t.string "employee"
    t.decimal "total"
    t.bigint "cost_sheet_id"
    t.index ["cost_sheet_id"], name: "index_time_sheets_on_cost_sheet_id"
    t.index ["employee_id"], name: "index_time_sheets_on_employee_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

end
